# Generated by Django 3.1.4 on 2020-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201230_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='eating_option',
            field=models.CharField(choices=[('Collection', 'Collection'), ('Delivery', 'Delivery')], max_length=200, null=True),
        ),
    ]
